source 'https://rubygems.org'

gem 'sinatra', '~> 3.0'
gem 'puma', '~> 6.0'
gem 'rack', '~> 2.2'
gem 'json'
gem 'dotenv'
gem 'logger'

group :development, :test do
  gem 'rspec', '~> 3.12'
  gem 'rack-test'
end