# frozen_string_literal: true

source 'https://rubygems.org'

ruby '~> 3.2'

# Web framework
gem 'sinatra',       '~> 3.2'
gem 'sinatra-contrib', '~> 3.2'
gem 'puma',          '~> 6.4'
gem 'rack-cors',     '~> 2.0'

# Databases
gem 'pg',    '~> 1.5'
gem 'mongo', '~> 2.20'

# Authentication
gem 'jwt', '~> 2.8'

# HTTP client
gem 'httparty', '~> 0.21'

# Background scheduler
gem 'rufus-scheduler', '~> 3.9'

# Utilities
gem 'dotenv', '~> 3.1'
gem 'json',   '~> 2.7'
gem 'logger', '~> 1.6'

group :test do
  gem 'rack-test', '~> 2.1'
  gem 'rspec',     '~> 3.13'
end
